### ISSUE TITLE
TypeError: Cannot set property 'ttl' of undefined

### ISSUE THREAD

**Issue by bgobi1991** [afharo/modem-serial#1]
Hi Sir, 
When I run the program,

/var/Projects/examples/modem-usb/node_modules/modem-serial/lib/index.js:29
    self.ttl = 3000;
             ^
TypeError: Cannot set property 'ttl' of undefined
    at ModemSerial (/var/Projects/examples/modem-usb/node_modules/modem-serial/lib/index.js:29:11)
    at Object.<anonymous> (/var/Projects/examples/modem-usb/app.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by afharo** [comment]
hi! which version of node are you using? this error is really unexpected

**Comment by afharo** [comment]
Closing this issue due to lack of details.
