### ISSUE TITLE
Error while installing the package

### ISSUE THREAD

**Issue by sasivarnan** [afharo/modem-serial#3]
I am getting the following error while I am trying to install this package. 

* OS - MacOS Mojavae 10.14.3
* Node.js - 10.15.2
* npm - 6.4.1

```sh
> serialport@1.7.4 install /Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node@10/10.15.2/bin/node',
node-pre-gyp verb cli   '/Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.7
node-pre-gyp info using node@10.15.2 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport/build/serialport/v1.7.4/Release/node-v64-darwin-x64/serialport.node" (not found)
node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:637:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:689:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:599:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node@10/10.15.2/bin/node" "/Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sasivarnanr/GitHub/sasivarnan/modem-serial-test/node_modules/modem-serial/node_modules/serialport
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN modem-serial-test@1.0.0 No description
npm WARN modem-serial-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sasivarnanr/.npm/_logs/2019-04-12T14_55_04_514Z-debug.log
```

@afharo  Kindly help.

**Comment by afharo** [comment]
Hi @sasivarnan 

Reading the logs you shared, I can see the installation error is due to failing to install the dependency `serialport`.

This repository is using the version 1.7.4 of this library and might not support NodeJS 10.

If you want to try updating the library (I can see `serialport` is now in the version 7.1.4: https://www.npmjs.com/package/serialport) and create a PR to fix it, I'll be happy to merge the update.
